title:            Talon Chandler
description:      
url:              # Site url.
signoff:          # Your name.
google_analytics: UA-110567746-1

links:
  - name:         Home
    url:          /
#  - name:         Writing
#    url:          /writing
#  - name: 	  Posts
#    url:	  /posts
  - name:	  Contact
    url:	  /contact
  - name:	  CV
    url:	  /cv.pdf
    
highlighter:      rouge
permalink:        pretty
markdown:         kramdown
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
