title:            Talon Chandler
description:      
url:              # Site url.
signoff:          # Your name.
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Writing
    url:          /
  - name:	  Contact
    url:	  /contact
  - name:	  CV
    url:	  /CV.pdf
    
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
